apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../.cache/manifests/stacks/ibm/application/dex-auth
configMapGenerator:
- name: dex-parameters
  behavior: merge
  literals:
  - github_hostname=github.ibm.com
  - github_org_name=kubeflow
